name: db
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=spring
    volumes:
      - data:/var/lib/mysql
volumes:
  data: